name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Show JDK version
        run: |
          java --version
          
      - name: Build SpringBoot Server
        run: |
          echo ${{ secrets.APPLICATION_SECRET }} | base64 --decode > ./src/main/resources/application_secret.yml
          chmod 700 ./mvnw
          ./mvnw clean package -Dtestskip
          
      - name: show directory
        run: |
          ls -a
          cd ./target
          ls -a

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
